language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

    # setup git for test commits
    - git config user.name "Test User"
    - git config user.email "test@test.test"

script: phpunit -c .travis-phpunit.xml
