language: php

env:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

before_script:

    # load dependencies
    - sed -i "s/\"~2.3\"/\"$SYMFONY_VERSION\"/g" composer.json
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

    # setup git for test commits
    - git config --global user.name "Test User"
    - git config --global user.email "test@test.test"

script: phpunit -c .travis-phpunit.xml
